# Generated by Django 3.2 on 2021-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderHeadLine', models.CharField(max_length=50)),
                ('SliderDes', models.TextField(max_length=150)),
                ('SliderButton', models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default=0, max_length=1)),
                ('ButtonText', models.CharField(blank=True, default='Click Here', max_length=50, null=True)),
                ('SliderImg', models.ImageField(upload_to='Carousel/')),
            ],
        ),
    ]
