# Generated by Django 3.2 on 2021-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCarousel', '0002_carousel_slidertextposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('ShortText', models.TextField(max_length=250)),
                ('Image', models.ImageField(upload_to='Feature/')),
            ],
        ),
        migrations.CreateModel(
            name='HeadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadingTitle', models.CharField(max_length=50)),
                ('ShortText', models.TextField(max_length=250)),
                ('Image', models.ImageField(upload_to='Heading/')),
            ],
        ),
    ]
